### ISSUE TITLE
Modding the Main Menu

### ISSUE THREAD

**Issue by Ibrahim9999** [HyperPolygon64/Sonic-06-Toolkit#2]
Which file contains the information for the main menu of the game? I want to be able to add all the characters to the multiplayer mode, but after examining the wiki I'm not sure which file that is

**Comment by HyperPolygon64** [comment]
The wiki is incomplete - text data is in `text.arc` and the main menu text is in `msg_mainmenu.e.mst`.

**Comment by HyperPolygon64** [comment]
Adding new menu slots is currently not possible in '06.

**Comment by Ibrahim9999** [comment]
So how did Legacy of Solaris do it? They added all the characters to the single player mode

**Comment by HyperPolygon64** [comment]
That's unrelated to MST and uses the DLC menu slots.

**Comment by HyperPolygon64** [comment]
[Added MST information to the wiki](https://github.com/HyperPolygon64/Sonic-06-Toolkit/wiki/Text-editing) - issue closed due to being an unrelated issue to Sonic '06 Toolkit directly.
